#!/bin/bash
# Used to send a defined number of cluster commands to a device, this is strictly
# for evaluating the fingerprinting attack module. This batch script has been
# almost generated by Gemini AI.

# 1. Validate that at least the command argument was provided
if [ -z "$1" ]; then
    echo "[-] Error: No Matter command provided."
    echo "Usage: $0 \"<matter_command>\" [iterations]"
    echo "Example: $0 \"onoff toggle 1 1\" 100"
    exit 1
fi

MATTER_COMMAND="$1"

# 2. Check for the iterations argument; default to 100 if empty or not a number
if [ -n "$2" ] && [ "$2" -eq "$2" ] 2>/dev/null; then
    TOTAL_REQUESTS="$2"
else
    TOTAL_REQUESTS=100
    echo "[*] No iteration count specified (or invalid). Defaulting to 100."
fi

INTERVAL_SECONDS=10
PIPE=/tmp/chiptool_pipe

echo "[*] Preparing to test command: \"$MATTER_COMMAND\""
echo "[*] Configuration: $TOTAL_REQUESTS requests, spaced $INTERVAL_SECONDS seconds apart."

# 3. Setup the clean Named Pipe (FIFO)
rm -f "$PIPE"
mkfifo "$PIPE"

# 4. Launch chip-tool in interactive mode, feeding it from the pipe
exec 3<>"$PIPE"
./chip-tool-1.6 interactive start --storage-directory matter24thJune/chiptool <"$PIPE" &
CHIP_PID=$!

echo "[*] Initialized chip-tool interactive mode (PID: $CHIP_PID)"
sleep 3 # Allow the interactive shell to fully initialize

# 5. Automation loop
for (( i=1; i<=TOTAL_REQUESTS; i++ ))
do
    echo "[*] ($(date +"%H:%M:%S")) Sending request $i/$TOTAL_REQUESTS..."
    
    # Inject the user's custom command parameter into the pipe
    echo "$MATTER_COMMAND" > "$PIPE"
    
    # Sleep for the designated tracking window, unless it's the final loop
    if [ $i -lt $TOTAL_REQUESTS ]; then
        sleep "$INTERVAL_SECONDS"
    fi
done

# 6. Clean teardown
echo "[*] Completed all iterations. Shutting down interactive mode safely..."
echo "exit" > "$PIPE"

# Close the file descriptor and delete the pipe file
exec 3>&-
rm -f "$PIPE"

# Wait for the background process to finish executing cleanly
wait $CHIP_PID
echo "[*] Testing session completed successfully."
